services:
  backend:
    build: ./backend
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    container_name: stockviz-backend
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    command: npm run start -- --host
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    container_name: stockviz-frontend
    depends_on:
      - backend
    restart: always

volumes:
  backend_node_modules:
  frontend_node_modules: